version: "3"

networks:
  gateway:
    external: true

services:
  traefik:
    image: traefik:latest
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    networks:
      - gateway
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock