name: global-docker

networks:
  default:
    name: traefik
    driver: bridge
    ipam:
      config:
        - gateway: 172.20.0.1
          subnet: 172.20.0.0/24
  solidtime:
    driver: bridge

volumes:
  portainer-data:
  pgadmin-data:
  solidtime-db-data:
  solidtime-log-data:
  solidtime-app-data:

services:
  traefik:
    image: traefik:v3.2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.docker.network: traefik
    ports:
      - '80:80'

  portainer:
    image: portainer/portainer-ee:2.24.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      traefik.enable: 'true'
      traefik.http.routers.portainer.rule: Host(`portainer.localhost`)
      traefik.http.routers.portainer.entrypoints: http
      traefik.http.routers.portainer.service: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000

  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: hello@kvd.studio
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5000
    volumes:
      - pgadmin-data:/pgadmin
    labels:
      traefik.enable: 'true'
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.localhost`)
      traefik.http.routers.pgadmin.entrypoints: http
      traefik.http.routers.pgadmin.service: pgadmin
      traefik.http.services.pgadmin.loadbalancer.server.port: 5000

  semaphore:
    image: semaphoreui/semaphore:v2.13.12
    restart: unless-stopped
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
    labels:
      traefik.enable: 'true'
      traefik.http.routers.semaphore.rule: Host(`semaphore.localhost`)
      traefik.http.routers.semaphore.entrypoints: http
      traefik.http.routers.semaphore.service: semaphore
      traefik.http.services.semaphore.loadbalancer.server.port: 3000

  registry:
    image: registry:3
    restart: unless-stopped
    labels:
      traefik.enable: 'true'
      traefik.http.routers.registry.rule: Host(`registry.localhost`)
      traefik.http.routers.registry.entrypoints: http
      traefik.http.routers.registry.service: registry
      traefik.http.services.registry.loadbalancer.server.port: 5000

  ### Solidtime
  solidtime-app:
    restart: unless-stopped
    image: "solidtime/solidtime:${SOLIDTIME_IMAGE_TAG:-latest}"
    user: "1000:1000"
    networks:
      - solidtime
      - default
    volumes:
      - "solidtime-app-data:/var/www/html/storage"
      - "solidtime-log-data:/var/www/html/storage/logs"
      - "./solidtime-app-storage:/var/www/html/storage/app"
    environment:
      CONTAINER_MODE: http
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8000/health-check/up" ]
    env_file:
      - .env
    depends_on:
      - solidtime-database
    labels:
      traefik.enable: 'true'
      traefik.http.routers.solidtime.rule: Host(`solidtime.localhost`)
      traefik.http.routers.solidtime.entrypoints: http
      traefik.http.routers.solidtime.service: solidtime
      traefik.http.services.solidtime.loadbalancer.server.port: 8000

  solidtime-scheduler:
    restart: unless-stopped
    image: "solidtime/solidtime:${SOLIDTIME_IMAGE_TAG:-latest}"
    user: "1000:1000"
    networks:
      - solidtime
    volumes:
      - "solidtime-app-data:/var/www/html/storage"
      - "solidtime-log-data:/var/www/html/storage/logs"
      - "./solidtime-app-storage:/var/www/html/storage/app"
    environment:
      CONTAINER_MODE: scheduler
    healthcheck:
      test: [ "CMD", "healthcheck" ]
    env_file:
      - .env
    depends_on:
      - solidtime-database

  solidtime-queue:
    restart: unless-stopped
    image: "solidtime/solidtime:${SOLIDTIME_IMAGE_TAG:-latest}"
    user: "1000:1000"
    networks:
      - solidtime
    volumes:
      - "solidtime-app-data:/var/www/html/storage"
      - "./solidtime-app-storage:/var/www/html/storage/app"
    environment:
      CONTAINER_MODE: worker
      WORKER_COMMAND: "php /var/www/html/artisan queue:work"
    healthcheck:
      test: [ "CMD", "healthcheck" ]
    env_file:
      - .env
    depends_on:
      - solidtime-database

  solidtime-database:
    restart: unless-stopped
    image: 'postgres:15'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - solidtime-db-data:/var/lib/postgresql/data
    networks:
      - solidtime
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  solidtime-gotenberg:
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    networks:
      - solidtime
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:3000/health" ]
