name: global-docker

networks:
  default:
    name: traefik
    driver: bridge
    ipam:
      config:
        - gateway: 172.20.0.1
          subnet: 172.20.0.0/24

volumes:
  portainer-data:
  pgadmin-data:

services:
  traefik:
    image: traefik:v3.2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.rule: Host(`traefik.localhost`)
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.docker.network: traefik
    ports:
      - '80:80'

  portainer:
    image: portainer/portainer-ee:2.24.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      traefik.enable: 'true'
      traefik.http.routers.portainer.rule: Host(`portainer.localhost`)
      traefik.http.routers.portainer.entrypoints: http
      traefik.http.routers.portainer.service: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000

  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: hello@kvd.studio
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5000
    volumes:
      - pgadmin-data:/pgadmin
    labels:
      traefik.enable: 'true'
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.localhost`)
      traefik.http.routers.pgadmin.entrypoints: http
      traefik.http.routers.pgadmin.service: pgadmin
      traefik.http.services.pgadmin.loadbalancer.server.port: 5000

  semaphore:
    image: semaphoreui/semaphore:v2.13.12
    restart: unless-stopped
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
    labels:
      traefik.enable: 'true'
      traefik.http.routers.semaphore.rule: Host(`semaphore.localhost`)
      traefik.http.routers.semaphore.entrypoints: http
      traefik.http.routers.semaphore.service: semaphore
      traefik.http.services.semaphore.loadbalancer.server.port: 3000

  registry:
    image: registry:3
    restart: unless-stopped
    labels:
      traefik.enable: 'true'
      traefik.http.routers.registry.rule: Host(`registry.localhost`)
      traefik.http.routers.registry.entrypoints: http
      traefik.http.routers.registry.service: registry
      traefik.http.services.registry.loadbalancer.server.port: 5000
