version: "3"

networks:
  default:
    name: gateway
    driver: bridge

services:
  traefik:
    image: traefik:latest
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.docker.network=gateway"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock